### ISSUE TITLE
Error in WebJobUsageDaily ?

### ISSUE THREAD

**Issue by truonghcit** [Microsoft/AzureUsageAndBillingPortal#69]
Hello,

I have an error in the WebJobUsageDaily Job. You can find the log of this webjob below.

Could you please help me treat this problem ?

Thanks in advanced,

Best regards,

Cao

[06/01/2017 14:35:24 > 85aa8c: SYS INFO] Status changed to Running
[06/01/2017 14:35:24 > 85aa8c: INFO] WebJobUsageDaily.exe Information: 0 : *************************************************************************
[06/01/2017 14:35:24 > 85aa8c: INFO] WebJobUsageDaily.exe Information: 0 : WebJobUsageDaily:Main starting. DateTime UTC: 6/1/2017 2:35:24 PM
[06/01/2017 14:35:25 > 85aa8c: INFO] Error indexing method 'Functions.TimerJob'
[06/01/2017 14:35:25 > 85aa8c: INFO] Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.TimerJob' ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'WebJobUsageDaily.Functions' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
[06/01/2017 14:35:25 > 85aa8c: INFO]    at WebJobUsageDaily.Functions..cctor()
[06/01/2017 14:35:25 > 85aa8c: INFO]    --- End of inner exception stack trace ---
[06/01/2017 14:35:25 > 85aa8c: INFO]    at WebJobUsageDaily.Functions.MyDailySchedule..ctor()
[06/01/2017 14:35:25 > 85aa8c: INFO]    --- End of inner exception stack trace ---
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
[06/01/2017 14:35:25 > 85aa8c: ERR ] 
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.Activator.CreateInstance(Type type)
[06/01/2017 14:35:25 > 85aa8c: ERR ] Unhandled Exception: Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.TimerJob' ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'WebJobUsageDaily.Functions' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
[06/01/2017 14:35:25 > 85aa8c: INFO]    at Microsoft.Azure.WebJobs.Extensions.Timers.TimerSchedule.Create(TimerTriggerAttribute attribute, INameResolver nameResolver)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at WebJobUsageDaily.Functions..cctor()
[06/01/2017 14:35:25 > 85aa8c: INFO]    at Microsoft.Azure.WebJobs.Extensions.Timers.Bindings.TimerTriggerAttributeBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    --- End of inner exception stack trace ---
[06/01/2017 14:35:25 > 85aa8c: INFO]    at Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.<TryCreateAsync>d__2.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at WebJobUsageDaily.Functions.MyDailySchedule..ctor()
[06/01/2017 14:35:25 > 85aa8c: INFO] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    --- End of inner exception stack trace ---
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsyncCore>d__14.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
[06/01/2017 14:35:25 > 85aa8c: INFO] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Activator.CreateInstance(Type type)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Extensions.Timers.TimerSchedule.Create(TimerTriggerAttribute attribute, INameResolver nameResolver)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__13.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Extensions.Timers.Bindings.TimerTriggerAttributeBindingProvider.TryCreateAsync(TriggerBindingProviderContext context)
[06/01/2017 14:35:25 > 85aa8c: INFO]    --- End of inner exception stack trace ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.<TryCreateAsync>d__2.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: INFO]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__13.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: INFO] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsyncCore>d__14.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: INFO]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__9.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__13.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ]    --- End of inner exception stack trace ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexMethodAsync>d__13.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__9.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.<CreateAsync>d__11.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.<GetAsync>d__10.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__5.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__4.MoveNext()
[06/01/2017 14:35:25 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:25 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.JobHost.<CreateContextAndLogHostStartedAsync>d__44.MoveNext()
[06/01/2017 14:35:26 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__27.MoveNext()
[06/01/2017 14:35:26 > 85aa8c: ERR ] --- End of stack trace from previous location where exception was thrown ---
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.JobHost.Start()
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
[06/01/2017 14:35:26 > 85aa8c: ERR ]    at WebJobUsageDaily.Program.Main()
[06/01/2017 14:35:26 > 85aa8c: SYS ERR ] Job failed due to exit code -532462766
[06/01/2017 14:35:26 > 85aa8c: SYS INFO] Process went down, waiting for 60 seconds
[06/01/2017 14:35:26 > 85aa8c: SYS INFO] Status changed to PendingRestart

**Comment by tdjastrzebski** [comment]
It seems like error occurs WebJobUsageDaily.Functions class static constructor
Probably you are missing app.config JobDailySchedule setting
