### ISSUE TITLE
WebJobBillingData Functions.ProcessQueueMessage failling

### ISSUE THREAD

**Issue by yogaanandk** [Microsoft/AzureUsageAndBillingPortal#82]
Hi 

WebJobBillingData is failing with below error

Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.ProcessQueueMessage ---> System.NullReferenceException: Object reference not set to an instance of an object.
 at WebJobBillingData.Functions.ProcessQueueMessage(BillingRequest billingRequest, TextWriter logWriter)
 at lambda_method(Closure , Functions , Object[] )
 at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`1.InvokeAsync(TReflected instance, Object[] arguments)
 at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`1.<InvokeAsync>d__8.MoveNext()
  
Please assist

**Comment by mustafakasap** [comment]
@jobalbz  you can make a pull request for this fix and I can commit

**Comment by jobalbz** [comment]
@mustafakasap we can now pull data with that fix. Thanks

**Comment by alexchx** [comment]
@jobalbz Committed a fix in PR #85

**Comment by alexchx** [comment]
@mustafakasap Committed a fix in PR #85
